# mosquitto/config/mosquitto.conf  (remplace la config de l'image)

# port clair pour tests
listener 1883
allow_anonymous true

# port TLS
listener 8883
protocol mqtt
cafile /mosquitto/certs/ca.crt
certfile /mosquitto/certs/server.crt
keyfile /mosquitto/certs/server.key
require_certificate false
